#!/usr/bin/env bash
#
# Returns 0 if the verison of cj-csp-json.h commited in git matches the
# one generated by scripts/single-header-make.sh

set -x

CJ_DIR=$(git rev-parse --show-toplevel)

"${CJ_DIR}/scripts/single-header-make.sh"
git status -s "${CJ_DIR}/cj-csp-json.h" | grep 'cj-csp-json.h'
if [ $? -eq 1 ]; then
  exit 0
fi
exit 1 # catches grep status=2 (error).
