name: csp-json-test
run-name: ${{ github.ref }} by ${{ github.actor }}
on: [push]
jobs:
  csp-json-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }}."
      - run: echo "Running on ${{ runner.os }}."
      - name: Check out
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - name: Build
        working-directory: ${{github.workspace}}
        run: ./scripts/build.sh
      - name: Test
        working-directory: ${{github.workspace}}
        run: ./scripts/test.sh
      - name: Is single header commited?
        working-directory: ${{github.workspace}}
        run: ./scripts/single-header-is-commited.sh
